# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'walkprint' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for walkprint
  pod 'AppLovinMediationGoogleAdapter'
  pod 'AppLovinSDK'
end
